services:
  - type: web
    name: nutrithrive
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATA_FILE_PATH
        value: app/data/Recipe.csv
      - key: API_HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: https://nutrithrive.onrender.com
